# 指定网站的基本URL地址
base_url = "https://mj.gujiakai.top"
# 网站标题
title = "Midjourney归档"
# 网站描述
description = "保存合租Midjourney的对话"

# 主题
# theme = ""

# 指定生成的网站文件的输出目录
output_dir = "public"
# 是否在输出目录中保留以点开头的文件和目录
preserve_dotfiles_in_output = false
# 是否在构建网站时编译Sass文件
compile_sass = true
# 是否在构建网站时压缩HTML文件
minify_html = true
# 指定哪些文件或文件夹应该在构建网站时被忽略
ignored_content = []
# 指定是否自动生成RSS（Really Simple Syndication）订阅链接
generate_feed = true
# 用于指定生成的RSS订阅链接的文件名
feed_filename = "atom.xml"
# 指定生成的RSS订阅链接中包含的文章条目数量
feed_limit = 20
# 指定是否在构建网站时使用硬链接（hard link）来处理static目录中的文件
hard_link_static = false
# 是否构建索引
build_search_index = true

[markdown]
# 代码块高亮
highlight_code = true
# 代码块高亮主题
highlight_theme = "material-dark"
# 是否渲染emoji
render_emoji = true
# 是否在新标签页中打开外部链接
external_links_target_blank = true
# 是否在外部链接上添加nofollow属性
external_links_no_follow = true
# 是否在外部链接上添加noreferrer属性
external_links_no_referrer = false
# 指定是否在渲染网站时使用智能标点符号
smart_punctuation = false

# 一个配置选项，用于指定在构建网站时记录哪些级别的日志
internal_level = "error"
# 一个配置选项，用于指定在构建网站时记录哪些级别的日志
# 与internal_level选项不同的是，external_level选项用于控制与Zola SSG框架外部相关的库或工具的日志记录级
external_level = "error"

# 用于指定如何生成页面和文章的URL slug
[slugify]
# 是否在生成页面和文章的URL slug时包含路径信息
paths = "off"
# 是否在生成页面和文章的URL slug时包含分类信息
taxonomies = "off"
# 是否在生成页面和文章的URL slug时包含锚点信息
anchors = "off"
# 是否在生成页面和文章的URL slug时保留日期信息
paths_keep_dates = false

[search]
# 是否在搜索结果中包含页面或文章的标题
include_title = true
# 指定是否在搜索结果中包含页面或文章的描述
include_description = false
# 指定是否在搜索结果中包含页面或文章的路径
include_path = false
# 是否在搜索结果中包含页面或文章的内容
include_content = true
# 在搜索结果中包含内容时，内容应该被截断的长度
truncate_content_length = 100
# 指定搜索索引的格式
index_format = "elasticlunr_json"

[extra]